---
# Dependabot

version: 2
enable-beta-ecosystems: true
updates:

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ignore patch updates for all dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
...
